// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4wQi1k5Teqvt1ykUzSNRyQdIug_xqDVc',
    appId: '1:805330133284:web:d2bb02d6d992ad12f0d3b1',
    messagingSenderId: '805330133284',
    projectId: 'doctorapp-3c2f9',
    authDomain: 'doctorapp-3c2f9.firebaseapp.com',
    storageBucket: 'doctorapp-3c2f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxzp3SAq_qe-cXjxNKQRTUtKzgTa9zL7g',
    appId: '1:805330133284:android:27a986b3eafc99b4f0d3b1',
    messagingSenderId: '805330133284',
    projectId: 'doctorapp-3c2f9',
    storageBucket: 'doctorapp-3c2f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp6sUFe0R_gqz9ceJRRhQCJ-IyalJ_Fo8',
    appId: '1:805330133284:ios:7a0b08b698cede4ef0d3b1',
    messagingSenderId: '805330133284',
    projectId: 'doctorapp-3c2f9',
    storageBucket: 'doctorapp-3c2f9.appspot.com',
    iosClientId: '805330133284-5ggbo8dkkej3162pbueft8h1rtq7ppos.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp6sUFe0R_gqz9ceJRRhQCJ-IyalJ_Fo8',
    appId: '1:805330133284:ios:7a0b08b698cede4ef0d3b1',
    messagingSenderId: '805330133284',
    projectId: 'doctorapp-3c2f9',
    storageBucket: 'doctorapp-3c2f9.appspot.com',
    iosClientId: '805330133284-5ggbo8dkkej3162pbueft8h1rtq7ppos.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorApp',
  );
}
